/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as BuildersRouteImport } from './routes/builders'
import { Route as BuyRouteImport } from './routes/buy'
import { Route as DreamValleyPhase2RouteImport } from './routes/dream-valley-phase-2'
import { Route as InsightsRouteImport } from './routes/insights'
import { Route as NewLaunchesRouteImport } from './routes/new-launches'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as PropertiesRouteImport } from './routes/properties'
import { Route as RentRouteImport } from './routes/rent'
import { Route as AdminLeadsRouteImport } from './routes/admin.leads'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const BuildersRoute = BuildersRouteImport.update({
  id: '/builders',
  path: '/builders',
  getParentRoute: () => rootRouteImport,
} as any)
const BuyRoute = BuyRouteImport.update({
  id: '/buy',
  path: '/buy',
  getParentRoute: () => rootRouteImport,
} as any)
const DreamValleyPhase2Route = DreamValleyPhase2RouteImport.update({
  id: '/dream-valley-phase-2',
  path: '/dream-valley-phase-2',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsRoute = InsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => rootRouteImport,
} as any)
const NewLaunchesRoute = NewLaunchesRouteImport.update({
  id: '/new-launches',
  path: '/new-launches',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const PropertiesRoute = PropertiesRouteImport.update({
  id: '/properties',
  path: '/properties',
  getParentRoute: () => rootRouteImport,
} as any)
const RentRoute = RentRouteImport.update({
  id: '/rent',
  path: '/rent',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLeadsRoute = AdminLeadsRouteImport.update({
  id: '/admin/leads',
  path: '/admin/leads',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/builders': typeof BuildersRoute
  '/buy': typeof BuyRoute
  '/dream-valley-phase-2': typeof DreamValleyPhase2Route
  '/insights': typeof InsightsRoute
  '/new-launches': typeof NewLaunchesRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/properties': typeof PropertiesRoute
  '/rent': typeof RentRoute
  '/admin/leads': typeof AdminLeadsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/builders': typeof BuildersRoute
  '/buy': typeof BuyRoute
  '/dream-valley-phase-2': typeof DreamValleyPhase2Route
  '/insights': typeof InsightsRoute
  '/new-launches': typeof NewLaunchesRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/properties': typeof PropertiesRoute
  '/rent': typeof RentRoute
  '/admin/leads': typeof AdminLeadsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/builders': typeof BuildersRoute
  '/buy': typeof BuyRoute
  '/dream-valley-phase-2': typeof DreamValleyPhase2Route
  '/insights': typeof InsightsRoute
  '/new-launches': typeof NewLaunchesRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/properties': typeof PropertiesRoute
  '/rent': typeof RentRoute
  '/admin/leads': typeof AdminLeadsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/builders'
    | '/buy'
    | '/dream-valley-phase-2'
    | '/insights'
    | '/new-launches'
    | '/privacy-policy'
    | '/properties'
    | '/rent'
    | '/admin/leads'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/builders'
    | '/buy'
    | '/dream-valley-phase-2'
    | '/insights'
    | '/new-launches'
    | '/privacy-policy'
    | '/properties'
    | '/rent'
    | '/admin/leads'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/builders'
    | '/buy'
    | '/dream-valley-phase-2'
    | '/insights'
    | '/new-launches'
    | '/privacy-policy'
    | '/properties'
    | '/rent'
    | '/admin/leads'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BuildersRoute: typeof BuildersRoute
  BuyRoute: typeof BuyRoute
  DreamValleyPhase2Route: typeof DreamValleyPhase2Route
  InsightsRoute: typeof InsightsRoute
  NewLaunchesRoute: typeof NewLaunchesRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  PropertiesRoute: typeof PropertiesRoute
  RentRoute: typeof RentRoute
  AdminLeadsRoute: typeof AdminLeadsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/builders': {
      id: '/builders'
      path: '/builders'
      fullPath: '/builders'
      preLoaderRoute: typeof BuildersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buy': {
      id: '/buy'
      path: '/buy'
      fullPath: '/buy'
      preLoaderRoute: typeof BuyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dream-valley-phase-2': {
      id: '/dream-valley-phase-2'
      path: '/dream-valley-phase-2'
      fullPath: '/dream-valley-phase-2'
      preLoaderRoute: typeof DreamValleyPhase2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights': {
      id: '/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof InsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/new-launches': {
      id: '/new-launches'
      path: '/new-launches'
      fullPath: '/new-launches'
      preLoaderRoute: typeof NewLaunchesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/properties': {
      id: '/properties'
      path: '/properties'
      fullPath: '/properties'
      preLoaderRoute: typeof PropertiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rent': {
      id: '/rent'
      path: '/rent'
      fullPath: '/rent'
      preLoaderRoute: typeof RentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/leads': {
      id: '/admin/leads'
      path: '/admin/leads'
      fullPath: '/admin/leads'
      preLoaderRoute: typeof AdminLeadsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BuildersRoute: BuildersRoute,
  BuyRoute: BuyRoute,
  DreamValleyPhase2Route: DreamValleyPhase2Route,
  InsightsRoute: InsightsRoute,
  NewLaunchesRoute: NewLaunchesRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  PropertiesRoute: PropertiesRoute,
  RentRoute: RentRoute,
  AdminLeadsRoute: AdminLeadsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
